### ISSUE TITLE
Feature: enemies track towards command center

### ISSUE THREAD

**Issue by tsamb** [tsamb/rts-tower-defence#7]
Enemies will have a target that they move towards. Enemies will be instantiated with the command center as the default target. This requires a "direction" which can be multiplied by a speed.

Eventually, enemies may have their own intelligence and can choose which building to target.

**Comment by Flamdoodle** [comment]
Thought:  Will this create a "Safe Zone" where Mines and Plants can be placed without fear of them being destroyed?

If so, consider making it random as to whether or not the spawning enemy will have the command center as a target.

**Comment by tsamb** [comment]
@Flamdoodle nice catch. Yes, at the moment enemies will still spawn on the back wall and track towards the command center. So I guess in this iteration, there will be a safe space in the rear corners which won't ever be in the line of fire. I'm kind of interested to see what sort of strategies this encourages, so I'll probably leave it for awhile. Another addition pretty soon will be to allow enemies to spawn on the rear third of the top and bottom walls.

As for the future of the "safe zone", each enemy has a `target` property in which is stored a building that it is targeting. That target property can be set to any building on the board and the enemy will track towards it. So the set up is pretty extensible for moving to a system where some enemies target random buildings. The ultimate goal is to give each enemy its own AI, so it can make decisions about what building it should target given a specific enemy strategy.
